local colors = {
  black   = '#181818',
  gray1   = '#282828',
  gray2   = '#383838',
  gray3   = '#585858',
  gray4   = '#b8b8b8',
  gray5   = '#d8d8d8',
  gray6   = '#e8e8e8',
  white   = '#f8f8f8',
  red     = '#ab4642',
  orange  = '#dc9656',
  yellow  = '#f7ca88',
  green   = '#a1b56c',
  cyan    = '#86c1b9',
  blue    = '#7cafc2',
  magenta = '#ba8baf',
  brown   = '#a16946',
}

local highlights = {
  ColorColumn  = { bg = colors.gray1 },
  CurSearch    = { fg = colors.black, bg = colors.yellow },
  CursorLine   = { bg = colors.gray1 },
  CursorLineNr = { fg = colors.white, bg = colors.gray1 },
  LineNr       = { fg = colors.gray3, bg = colors.gray1 },
  MatchParen   = { bg = colors.gray2 },
  Normal       = { fg = colors.white, bg = colors.black },
  NormalFloat  = { fg = colors.white, bg = colors.gray1 },
  Search       = { bg = colors.gray2 },
  SignColumn   = { fg = colors.gray3, bg = colors.gray1 },
  Visual       = { bg = colors.gray2 },
  WarningMsg   = { fg = colors.yellow },
  ErrorMsg     = { fg = colors.red },
  Question     = { fg = colors.cyan },

  DiagnosticUnderlineError = { undercurl = true, sp = colors.red },
  DiagnosticUnderlineWarn  = { undercurl = true, sp = colors.yellow },
  DiagnosticUnderlineInfo  = { undercurl = true, sp = colors.blue },
  DiagnosticUnderlineHint  = { undercurl = true, sp = colors.gray4 },

  DiagnosticError = { fg = colors.red },
  DiagnosticWarn  = { fg = colors.yellow },
  DiagnosticInfo  = { fg = colors.blue },
  DiagnosticHint  = { fg = colors.gray4 },
  DiagnosticSignError = { fg = colors.red, bg = colors.gray1 },
  DiagnosticSignWarn = { fg = colors.yellow, bg = colors.gray1 },
  DiagnosticSignInfo = { fg = colors.blue, bg = colors.gray1 },
  DiagnosticSignHint = { fg = colors.gray4, bg = colors.gray1 },
  DiagnosticUnnecessary = { fg = colors.gray3 },
  DiagnosticDeprecated = { strikethrough = true },

  ['@attribute'] = { fg = colors.yellow },
  ['@attribute.builtin'] = { link = '@attribute' },
  ['@boolean'] = { fg = colors.orange },
  ['@character'] = { fg = colors.brown },
  ['@character.special'] = { fg = colors.brown },
  ['@comment'] = { fg = colors.gray3 },
  ['@constant'] = { fg = colors.orange },
  ['@constant.builtin'] = { fg = colors.cyan },
  ['@constructor'] = { fg = colors.cyan },
  ['@function'] = { fg = colors.blue },
  ['@function.builtin'] = { fg = colors.cyan },
  ['@function.macro'] = { fg = colors.red },
  ['@include'] = { fg = colors.cyan },
  ['@keyword'] = { fg = colors.magenta, italic = true },
  ['@keyword.import'] = { link = '@include' },
  ['@label'] = { fg = colors.red },
  ['@module'] = { fg = colors.cyan },
  ['@module.builtin'] = { link = '@module' },
  ['@number'] = { fg = colors.orange },
  ['@number.float'] = { link = '@number' },
  ['@operator'] = { fg = colors.gray5 },
  ['@property'] = { fg = colors.red },
  ['@punctuation'] = { fg = colors.brown },
  ['@punctuation.special'] = { fg = colors.brown },
  ['@string'] = { fg = colors.green },
  ['@string.escape'] = { fg = colors.brown },
  ['@string.special'] = { fg = colors.brown },
  ['@tag'] = { fg = colors.red },
  ['@tag.attribute'] = { fg = colors.yellow },
  ['@tag.builtin'] = { link = '@tag' },
  ['@tag.delimiter'] = { fg = colors.gray3 },
  ['@type'] = { fg = colors.yellow },
  ['@type.builtin'] = { link = '@type' },
  ['@variable'] = { fg = colors.white },
  ['@variable.builtin'] = { fg = colors.blue },
  ['@variable.member'] = { fg = colors.red },
  ['@variable.parameter.builtin'] = { fg = colors.blue },
  ['@diff.minus'] = { fg = colors.red },
  ['@diff.plus'] = { fg = colors.green },

  ['@lsp.type.builtinType'] = { fg = colors.yellow },
  ['@lsp.type.decorator'] = {},
  ['@lsp.type.lifetime'] = { fg = colors.cyan },
  ['@lsp.type.macro'] = { fg = colors.red },
  ['@lsp.type.method'] = {},

  ['@markup.raw.block'] = { fg = colors.gray4 },
  ['@label.markdown'] = { fg = colors.gray4 },

  ['@tag.blade'] = { fg = colors.magenta },
  -- ['@lsp.mod.attribute'] = { fg = colors.red },

  ['@string.special.path.diff'] = { fg = colors.white },
  ['@punctuation.special.diff'] = {},

  ['@constructor.lua'] = {},

  ['@lsp.type.keyword.yaml.ansible'] = {},
  ['@lsp.type.class.yaml.ansible'] = {},

  LazyReasonPLugin = { fg = colors.cyan },
  LazyReasonStart = { fg = colors.red },
  LazyReasonCmd = { fg = colors.gray4 },
  LazyReasonFt = { fg = colors.yellow },
  LazyReasonEvent = { fg = colors.orange },
  LazyReasonSource = { fg = colors.green },
  LazyReasonImport = { fg = colors.white },
  LazyReasonRuntime = { fg = colors.magenta },
  LazyCommit = { fg = colors.blue },
  LazyCommitIssue = { fg = colors.magenta },
  LazyCommitType = { bold = true },
  LazyComment = { fg = colors.gray4 },
  LazyDimmed = { fg = colors.gray3 },
  LazyProp = { fg = colors.brown },
  LazyError = { fg = colors.red },
  LazySpecial = { fg = colors.brown },
  LazyLocal = { fg = colors.brown },

  IblIndent = { fg = colors.gray1 },
  IblScope = { fg = colors.gray3 },

  TelescopeNormal = { link = 'Normal' },
  TelescopeBorder = { fg = colors.gray4 },

  GitSignsAdd          = { fg = colors.green, bg = colors.gray1 },
  GitSignsChange       = { fg = colors.blue, bg = colors.gray1 },
  GitSignsChangedelete = { link = 'GitSignsChange' },
  GitSignsDelete       = { fg = colors.red, bg = colors.gray1 },
  GitSignsTopDelete    = { link = 'GitSignsDelete' },
  GitSignsUntracked    = { fg = colors.green, bg = colors.gray1 },
}

vim.g.colors_name = 'base16-default-dark'
vim.cmd.highlight('clear')

for group, hl in pairs(highlights) do
  hl.force = true
  hl.cterm = hl.cterm or {}
  vim.api.nvim_set_hl(0, group, hl)
end
