#!/usr/bin/env bash

lock_command="slock"

options="poweroff\nreboot"

if command -v $lock_command &> /dev/null; then
	options="${options}\nlock"
fi

option=$(echo -e $options | dmenu -p "Shutdown: " "$@")
echo "$option"

case $option in
	"poweroff")
        poweroff
		;;
	"reboot")
		reboot
		;;
	"lock")
		slock
		;;
	*)
esac

