#!/bin/bash

lock_command="slock"

options="shutdown\nreboot"

if command -v $lock_command &> /dev/null; then
	options="${options}\nlock"
fi

option=$(echo -e $options | dmenu -p "Shutdown: " "$@")
echo "$option"

case $option in
	"shutdown")
		shutdown now
		;;
	"reboot")
		reboot
		;;
	"lock")
		if command -v $lock_command &> /dev/null; then
			slock
		fi
		;;
	*)
esac

