#!/bin/bash

# A custom loaderbar script

# Check if there is only one argument
if [ $# -ne 1 ]; then
	command=$(basename $0)
	echo "Usage: $command <percentage>"
	exit 1
fi

# Check if the argument is a number
if ! ( echo $1 | egrep -q '^[0-9]+$' ); then
	echo "Error: percentage must be a number"
	exit 1
fi

# Check if the argument is between 0 and 100
if ! [ $1 -ge 0 ] || ! [ $1 -le 100 ]; then
	echo "Error: percentage must be between 0 and 100 inclusive"
	exit 1
fi

# Get terminal width
cols=$( tput cols )
cols=$(( $cols - 7 ))

# hashtagsnum=$(( (200*$cols/100*$1 % 2 + 100*$cols/100*$1) / 100 ))
hashtagsnum=$(( $cols * $1 / 100 ))
dotsnum=$(( $cols - $hashtagsnum ))

hashtags=$( printf "%-${hashtagsnum}s" "")
dots=$( printf "%-${dotsnum}s" "")

hashtags=${hashtags// /\#}
dots=${dots// /\.}

echo -ne "[${hashtags}${dots}] $1%\r"

