#!/usr/bin/env bash

function test_tar() {
  [[ "$(file "$1")" != *"POSIX tar archive"* ]] && return
	mkdir -p "$2"
	tar -xf "$1" -C "$2"
	rm "$1"
}

command=$(basename $0)

if [[ $# -ne 1 && $# -ne 2 ]]; then
  echo "Usage: $command <file> [destination folder]"
  exit
fi

if ! [[ -f $1 ]]; then
	echo "$command: $1: No such file of directory"
	exit
fi

file_name=$(basename $1)
dest_folder="${file_name%.*}"
ar_dest_folder="."

if [[ $# -eq 2 ]]; then
  dest_folder="$2"
	ar_dest_folder="$2"
fi

target_file="$(realpath "$1")"
dest_folder="$(realpath "$dest_folder")"
ar_dest_folder="$(realpath "$ar_dest_folder")"

case "$(file "$1")" in
  *"Zip archive data"*)
    unzip -qq -d "$dest_folder" "$target_file"
    ;;
  *"RAR archive data"*)
    mkdir -p "$dest_folder"
    unrar x -idq "$target_file" "$dest_folder"
    folder="$dest_folder/${file_name%.*}"
    mv "$folder"/* "$dest_folder"
    rm -rf "$folder"
    ;;
  *"gzip compressed data"*)
		mkdir -p "$ar_dest_folder"
		file="$ar_dest_folder/${file_name%.*}"
		gzip -dc < "$target_file" > "$file"
		dest_folder=${dest_folder%.*}
    test_tar $file $dest_folder
    ;;
	*"bzip2 compressed data"*)
		mkdir -p "$ar_dest_folder"
		file="$ar_dest_folder/${file_name%.*}"
		bzcat -kd < "$target_file" > "$file"
		dest_folder=${dest_folder%.*}
		test_tar $file $dest_folder
		;;
  *)
    echo "Unsupported file type"
    ;;
esac

