return {
  {
    'nvim-treesitter/nvim-treesitter',
    lazy = false,
    branch = 'main',
    build = ':TSUpdate',
    opts = {
      ensure_installed = {
        'asm',
        'bash',
        'blueprint',
        'c',
        'cmake',
        'cpp',
        'css',
        'diff',
        'dockerfile',
        'git_config',
        'git_rebase',
        'gitattributes',
        'gitcommit',
        'gitignore',
        'glsl',
        'go',
        'gomod',
        'gosum',
        'gowork',
        'graphql',
        'haskell',
        'html',
        'hyprlang',
        'java',
        'javascript',
        'json',
        'jsonc',
        'just',
        'lua',
        'make',
        'markdown',
        'meson',
        'php',
        'proto',
        'python',
        'requirements',
        'rust',
        'scss',
        'sql',
        'swift',
        'terraform',
        'toml',
        'tsx',
        'typescript',
        'xml',
        'yaml',
        'zig',
      },
    },
    config = function (_, opts)
      require('nvim-treesitter').install(opts.ensure_installed)
    end,
  },
}
